version: '3.9'


services:
  
  mysqldb:
    image: mysql:5.7
    restart: always 
    container_name: mysql_con
    volumes:
      - ./dbdata:/var/lib/mysql
    env_file:
      - ./config/.env
    ports:
      - 3306:3306
  
  webapp:
    depends_on:
      - mysqldb
    build: .
    container_name: email_template_con
    restart: always
    env_file:
      - ./config/.env
    volumes:
      - ./:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: ["node", "app.js"]

volumes: 
  dbdata:
